[package]
name = "iris"
version = "0.1.0"
edition = "2021"
type = "bin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.1.0"
clap = { version = "4.5.4", features = ["derive"] }
indoc = "2.0.5"
tokio = { version = "1.37.0", features = ["full"] }
